/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package pw.custom.androidcamera;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name="CustomAndroidCamera", id="pw.custom.androidcamera")
public class CustomAndroidCameraModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "CustomAndroidCameraModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public CustomAndroidCameraModule()
	{
		super();
	}
	
	@Kroll.constant
	public static final int RESOLUTION_HIGH = 0;
	
	@Kroll.constant
	public static final int RESOLUTION_LOW = 1;
	
	@Kroll.constant
	public static final int RESOLUTION_SCREEN = 2;
	
	@Kroll.constant
	public static final int RESOLUTION_480 = 3;
	
	@Kroll.constant
	public static final int RESOLUTION_720 = 4;
	
	@Kroll.constant
	public static final int RESOLUTION_1080 = 5;
	
	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(TAG, "example called");
		return "hello world";
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(TAG, "set example property: " + value);
	}

}

